services:
  - type: web
    name: chromium-api
    env: node
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "mongodb+srv://gugitia:cromado@chromiumcluster.ebl3qdv.mongodb.net/?retryWrites=true&w=majority&appName=chromiumCluster"
        sync: true
    plan: free
    region: oregon
