services:
  - type: web
    name: chromium-api
    env: node
    branch: productRoutes
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: "value: "mongodb+srv://render:render@chromiumcluster.ebl3qdv.mongodb.net/chromiumCluster?retryWrites=true&w=majority" "
        sync: true
    plan: free
    region: oregon
